package eduvault.ui;
import eduvault.model.RegisterResult;
import eduvault.model.User;
import eduvault.service.AuthService;
import eduvault.service.SessionManager;
import javax.swing.JOptionPane;

/**
 *
 * @author erdem
 */
public class ChangeMasterPasswordDialog extends javax.swing.JDialog {
    
    private char defaultCurrentPasswordEchoChar;
    private char defaultNewPasswordEchoChar;
    private char defaultRepeatPasswordEchoChar;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChangeMasterPasswordDialog.class.getName());

    /**
     * Creates new form ChangeMasterPasswordDialog
     */
    public ChangeMasterPasswordDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        defaultCurrentPasswordEchoChar = txtCurrentPassword.getEchoChar();
        defaultNewPasswordEchoChar = txtNewPassword.getEchoChar();
        defaultRepeatPasswordEchoChar = txtRepeatNewPassword.getEchoChar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField2 = new javax.swing.JPasswordField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCurrentPassword = new javax.swing.JPasswordField();
        chkShowCurrentPassword = new javax.swing.JCheckBox();
        txtNewPassword = new javax.swing.JPasswordField();
        chkShowNewPassword = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtRepeatNewPassword = new javax.swing.JPasswordField();
        chkShowRepeatNewPassword = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jCheckBox2.setText("Şifre Göster");

        jLabel3.setText("Mevcut Ana Şifre : ");

        jCheckBox3.setText("Şifre Göster");

        jLabel4.setText("Mevcut Ana Şifre : ");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ana Şifre Değiştir");

        jLabel2.setText("Mevcut Ana Şifre : ");

        chkShowCurrentPassword.setText("Şifre Göster");
        chkShowCurrentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowCurrentPasswordActionPerformed(evt);
            }
        });

        chkShowNewPassword.setText("Şifre Göster");
        chkShowNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowNewPasswordActionPerformed(evt);
            }
        });

        jLabel5.setText("Yeni Ana Şifre : ");

        chkShowRepeatNewPassword.setText("Şifre Göster");
        chkShowRepeatNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowRepeatNewPasswordActionPerformed(evt);
            }
        });

        jLabel6.setText("Yeni Ana Şifre Tekrar : ");

        btnChangePassword.setText("Şifreyi Değiştir");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnCancel.setText("Vazgeç");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chkShowNewPassword))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chkShowCurrentPassword))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtRepeatNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chkShowRepeatNewPassword)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkShowCurrentPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkShowNewPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRepeatNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkShowRepeatNewPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePassword)
                    .addComponent(btnCancel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkShowCurrentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowCurrentPasswordActionPerformed
        if (chkShowCurrentPassword.isSelected()) {
            txtCurrentPassword.setEchoChar((char) 0);
        } else {
            txtCurrentPassword.setEchoChar(defaultCurrentPasswordEchoChar);
        }
    }//GEN-LAST:event_chkShowCurrentPasswordActionPerformed

    private void chkShowNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowNewPasswordActionPerformed
        if (chkShowNewPassword.isSelected()) {
            txtNewPassword.setEchoChar((char) 0);
        } else {
            txtNewPassword.setEchoChar(defaultNewPasswordEchoChar);
        }
    }//GEN-LAST:event_chkShowNewPasswordActionPerformed

    private void chkShowRepeatNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowRepeatNewPasswordActionPerformed
        if (chkShowRepeatNewPassword.isSelected()) {
            txtRepeatNewPassword.setEchoChar((char) 0);
        } else {
            txtRepeatNewPassword.setEchoChar(defaultRepeatPasswordEchoChar);
        }
    }//GEN-LAST:event_chkShowRepeatNewPasswordActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        String currentPassword = new String(txtCurrentPassword.getPassword());
        String newPassword = new String(txtNewPassword.getPassword());
        String repeatNewPassword = new String(txtRepeatNewPassword.getPassword());

        if (!newPassword.equals(repeatNewPassword)) {
            JOptionPane.showMessageDialog(this, "Yeni parolalar eşleşmiyor!");
            return;
        }

        User currentUser = SessionManager.getCurrentUser();
        AuthService authService = new AuthService();

        RegisterResult result = authService.changeMasterPassword(currentUser, currentPassword, newPassword);

        if (result.isSuccess()) {
            JOptionPane.showMessageDialog(this, result.getMessage());
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, result.getMessage(), "Hata", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ChangeMasterPasswordDialog dialog = new ChangeMasterPasswordDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JCheckBox chkShowCurrentPassword;
    private javax.swing.JCheckBox chkShowNewPassword;
    private javax.swing.JCheckBox chkShowRepeatNewPassword;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField txtCurrentPassword;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtRepeatNewPassword;
    // End of variables declaration//GEN-END:variables
}
