package eduvault.ui;

import eduvault.model.User;
import eduvault.model.VaultEntry;
import eduvault.service.SessionManager;
import eduvault.service.VaultService;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import eduvault.model.VaultEntry;
import javax.swing.JOptionPane;
import eduvault.ui.ChangeMasterPasswordDialog;

/**
 *
 * @author erdem
 */
public class MainForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
    java.util.logging.Logger.getLogger(MainForm.class.getName());
    
    private javax.swing.Timer sessionTimer;

    private List<VaultEntry> currentEntries;
    private java.util.List<eduvault.model.VaultEntry> filteredEntries;

    public MainForm() {
        initComponents();
        
        setLocationRelativeTo(null);
        User user = SessionManager.getCurrentUser();

        if (user != null) {
            lblWelcome.setText("Hoşgeldiniz, " + user.getUsername());
        }

        txtDetailSiteName.setEditable(false);
        txtDetailUrl.setEditable(false);
        txtDetailUsername.setEditable(false);
        txtDetailPassword.setEditable(false);
        txtDetailNote.setEditable(false);

        loadEntries();
        startSessionTimer();
        
    }
    
        private void startSessionTimer() {
            sessionTimer = new javax.swing.Timer(10000, e -> {
                if (SessionManager.isSessionExpired() && !SessionManager.isManuallyLoggedOut()) {
                    SessionManager.logout();
                    JOptionPane.showMessageDialog(this, "Oturum zaman aşımına uğradı. Lütfen yeniden giriş yapın.");

                    LoginForm loginForm = new LoginForm();
                    loginForm.setVisible(true);
                    this.dispose();
                }
            });

            sessionTimer.start();
        }

    
    private void loadEntries() {
        try {
            User currentUser = SessionManager.getCurrentUser();

            if (currentUser == null) {
                return;
            }

            VaultService vaultService = new VaultService();
            currentEntries = vaultService.getDecryptedEntries(currentUser);
            filteredEntries = new java.util.ArrayList<>(currentEntries);

            refreshSiteList();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
        private void filterEntries() {
            String searchText = txtSearch.getText().trim().toLowerCase();

            filteredEntries = new java.util.ArrayList<>();

            if (currentEntries == null) {
                return;
            }

            for (VaultEntry entry : currentEntries) {
                if (entry.getSiteName().toLowerCase().contains(searchText)) {
                    filteredEntries.add(entry);
                }
            }

            refreshSiteList();
        }
    
        private void refreshSiteList() {
            javax.swing.DefaultListModel<String> listModel = new javax.swing.DefaultListModel<>();

            for (VaultEntry entry : filteredEntries) {
                listModel.addElement(entry.getSiteName());
            }

            lstSites.setModel(listModel);
            clearDetailFields();
        }
    
    private void showSelectedEntryDetails() {
        int selectedIndex = lstSites.getSelectedIndex();

        if (selectedIndex >= 0 && filteredEntries != null && selectedIndex < filteredEntries.size()) {
            eduvault.model.VaultEntry entry = filteredEntries.get(selectedIndex);

            txtDetailSiteName.setText(entry.getSiteName());
            txtDetailUrl.setText(entry.getSiteUrl());
            txtDetailUsername.setText(entry.getAccountUsername());
            txtDetailPassword.setText(entry.getDecryptedPassword());
            txtDetailNote.setText(entry.getNote());
        }
    }
    private void clearDetailFields() {
        txtDetailSiteName.setText("");
        txtDetailUrl.setText("");
        txtDetailUsername.setText("");
        txtDetailPassword.setText("");
        txtDetailNote.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnAddEntry = new javax.swing.JButton();
        btnEditEntry = new javax.swing.JButton();
        btnDeleteEntry = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSites = new javax.swing.JList<>();
        txtDetailSiteName = new javax.swing.JTextField();
        txtDetailUrl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDetailUsername = new javax.swing.JTextField();
        txtDetailPassword = new javax.swing.JTextField();
        txtDetailNote = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnChangeMasterPassword = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWelcome.setText("Hoş geldiniz");

        btnAddEntry.setText("Yeni Kayıt Ekle");
        btnAddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEntryActionPerformed(evt);
            }
        });

        btnEditEntry.setText("Düzenle");
        btnEditEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEntryActionPerformed(evt);
            }
        });

        btnDeleteEntry.setText("Sil");
        btnDeleteEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEntryActionPerformed(evt);
            }
        });

        btnRefresh.setText("Yenile");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnLogout.setText("Çıkış Yap");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lstSites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstSitesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstSites);

        jLabel1.setText("Site Adı :");

        jLabel2.setText("Site URL :");

        jLabel3.setText("Kullanıcı Adı :");

        jLabel4.setText("Şifre :");

        jLabel5.setText("Not :");

        txtDetailNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetailNoteActionPerformed(evt);
            }
        });

        jLabel6.setText("Ara :");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnChangeMasterPassword.setText("Ana Şifre Değiştir");
        btnChangeMasterPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeMasterPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearch))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDetailSiteName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addComponent(txtDetailUrl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDetailPassword)
                            .addComponent(txtDetailNote)
                            .addComponent(txtDetailUsername))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangeMasterPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDetailSiteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDetailUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDetailUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDetailPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtDetailNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(btnEditEntry)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnDeleteEntry))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAddEntry)
                                    .addGap(80, 80, 80)
                                    .addComponent(btnRefresh)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangeMasterPassword)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnLogout)
                            .addGap(6, 6, 6))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(9, 9, 9)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        SessionManager.updateLastActivity();
        loadEntries();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
            if (sessionTimer != null) {
                sessionTimer.stop();
            }

            SessionManager.logout();
            JOptionPane.showMessageDialog(this, "Çıkış yapıldı!");

            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEntryActionPerformed
        SessionManager.updateLastActivity();
        AddEntryDialog dialog = new AddEntryDialog(this, true);
        dialog.setVisible(true);
        loadEntries();
    }//GEN-LAST:event_btnAddEntryActionPerformed

    
    private void txtDetailNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetailNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetailNoteActionPerformed

    private void lstSitesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstSitesMouseClicked
        SessionManager.updateLastActivity();
        showSelectedEntryDetails();
    }//GEN-LAST:event_lstSitesMouseClicked

    private void btnDeleteEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEntryActionPerformed
            SessionManager.updateLastActivity();
            int selectedIndex = lstSites.getSelectedIndex();

            if (selectedIndex < 0 || filteredEntries == null || selectedIndex >= filteredEntries.size()) {
                JOptionPane.showMessageDialog(this, "Lütfen silmek için bir kayıt seçin!");
                return;
            }

            VaultEntry selectedEntry = filteredEntries.get(selectedIndex);
            User currentUser = SessionManager.getCurrentUser();

            VaultService vaultService = new VaultService();
            boolean result = vaultService.deleteVaultEntry(currentUser, selectedEntry.getId());

            if (result) {
                JOptionPane.showMessageDialog(this, "Kayıt silindi!");
                loadEntries();
            } else {
                JOptionPane.showMessageDialog(this, "Silme işlemi başarısız!");
            }
    }//GEN-LAST:event_btnDeleteEntryActionPerformed

    private void btnEditEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEntryActionPerformed
            SessionManager.updateLastActivity();
            int selectedIndex = lstSites.getSelectedIndex();

            if (selectedIndex < 0 || filteredEntries == null || selectedIndex >= filteredEntries.size()) {
                JOptionPane.showMessageDialog(this, "Lütfen düzenlemek için bir kayıt seçin!");
                return;
            }

            VaultEntry selectedEntry = filteredEntries.get(selectedIndex);

            EditEntryDialog dialog = new EditEntryDialog(this, true, selectedEntry);
            dialog.setVisible(true);

            loadEntries();
    }//GEN-LAST:event_btnEditEntryActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        filterEntries();
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        SessionManager.updateLastActivity();
        filterEntries();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnChangeMasterPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeMasterPasswordActionPerformed
        SessionManager.updateLastActivity();

        ChangeMasterPasswordDialog dialog = new ChangeMasterPasswordDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnChangeMasterPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new MainForm().setVisible(true));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEntry;
    private javax.swing.JButton btnChangeMasterPassword;
    private javax.swing.JButton btnDeleteEntry;
    private javax.swing.JButton btnEditEntry;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JList<String> lstSites;
    private javax.swing.JTextField txtDetailNote;
    private javax.swing.JTextField txtDetailPassword;
    private javax.swing.JTextField txtDetailSiteName;
    private javax.swing.JTextField txtDetailUrl;
    private javax.swing.JTextField txtDetailUsername;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
